version: "3"

services:
  phpldapadmin:
    build:
      context: ./phpldapadmin
    ports:
      - "10081:80"
    command: "/usr/bin/supervisord -nc /etc/supervisor/supervisord.conf"
    volumes:
      - ./phpldapadmin/ldap-account-manager:/var/lib/ldap-account-manager:rw
      - ./phpldapadmin/supervisor:/etc/supervisor:rw
      - ./phpldapadmin/log/supervisor:/var/log/supervisor:rw
    environment:
      - TZ=JST-9

  samba4:
    build:
      context: ./samba4
    command: "/entrypoint.sh '/usr/bin/supervisord -nc /etc/supervisor/supervisord.conf'"
    volumes:
      - ./samba4/samba:/etc/samba:rw
      - ./samba4/krb5.conf:/etc/krb5.conf:rw
      - ./samba4/supervisor:/etc/supervisor:rw
      - ./samba4/log/supervisor:/var/log/supervisor:rw
    environment:
      - TZ=JST-9
      - REALM_NAME=
      - DOMAIN_NAME=
      - DNS_BACKEND=
      - SERVER_ROLE=
      - ADMIN_PASS=

    privileged: true

